api_platform:
    title: 'ITFL.UZ'
    description: 'Created by KG-21.1 Group'
    version: '0.0.1'

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    patch_formats:
        json: ['application/merge-patch+json']

    collection:
        pagination:
            client_enabled: true
            items_per_page: 10

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
